backend:
  name: github
  repo: soseconsulting/sscsite  # Your GitHub repo name
  branch: main

media_folder: "images/uploads" # Adjust this if necessary
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Home"
        name: "home"
        file: "index.html"
        fields:
          - {label: "Title", name: "title", widget: "string"}
